version: '3'

services:
  registry:
    container_name: registry
    image: registry:2
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    volumes:
      - ./data:/var/lib/registry
      - ./auth:/auth
    ports:
      - "5000:5000" # Expose registry port

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
        #- ./certs:/etc/ssl/certs


